### ISSUE TITLE
There is no readme file

### ISSUE THREAD

**Issue by ivarboms** [maarten990/editor#1]
Things that are missing
- A readme file

**Comment by maarten990** [comment]
Issues will not be taken seriously without sufficient information.
In the future, please make sure to include:
- detailed steps to reproduce the issue
- full system specs (e.g. output from dxdiag, /proc/cpuinfo, etc)
- a personal phone number, address and a small picture in case I need to contact you
- a scan of a full medical test clearing you of, among others, HIV, hepatitis B/C, malaria and dengue fever.
- a link to your profile on any dating site of your choice, e.g. OKCupic, AdultFriendFinder, etc (Tinder will not suffice)
