### ISSUE TITLE
There is still no readme file

### ISSUE THREAD

**Issue by ivarboms** [maarten990/editor#2]
### Things that are still missing
-  [ ] A readme file
### Steps to reproduce issue:
- Be born
- Learn to read
- Find this repository
- Look for readme file
- Don't find readme file
### Information
- DxDiag output: http://pastebin.com/RZutZ3tS
- Name: Harald Rex
- Phone number: +47 22 04 87 00
- Fax number: +47 22 04 87 90
- Address: [Slottsplassen 1, 0010 Oslo, Norway](https://goo.gl/maps/umKoBSn49Ky)
-  Medical test scan: ![Medical test scan](http://i.imgur.com/QQNUB6G.png)
- Dating site profile: [OkCupid](https://www.okcupid.com/profile)

**Comment by maarten990** [comment]
Resolved by 34cdfca
